---
title: "sna-reexam"
author: "Luis Felipe Villota Macías"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# RE-EXAM ASSIGNMENT - SOCIAL NETWORK ANALYSIS MODULE: AIRLINES, IRON MAN MOVIE AND OTHERS

## Exploring social networks and analyzing their properties

## Loading packages

```{r message=FALSE, warning=FALSE}
library(tidyverse)	
library(psych)	
library(gridExtra)
library(readr)
library(skimr)
library(network)
library(plyr)
library(igraph)
library(intergraph)
library(sna)
library(RColorBrewer)
library(vcd)
library(ggplot2)
library(networkR)

```

### PART A:

#### AIRLINES (routes between cities)

```{r}
# Loading the data: Airlines database(s)



ldply(.data = "C:/Users/USER/Desktop/codebaker/all_r/social-network-analysis/sna-exam-using-social-theory/airlines.zip", .fun = unzip, exdir= dir)

edges = read.csv("C:/Users/USER/Desktop/codebaker/all_r/social-network-analysis/sna-exam-using-social-theory/airlines_edges_2.csv")

nodes = read.csv("C:/Users/USER/Desktop/codebaker/all_r/social-network-analysis/sna-exam-using-social-theory/airlines_nodes_2.csv")

```

```{r}


```
